
version: '3.8'
services:
  redis:
    container_name: redis
    ports:
      - '8000:8000'
    build: .
    networks:
      - internal

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    networks:
      - internal


networks:
 internal:
    



