version: '3.8'
services:

  postgres_orm:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  openldap:
      image: bitnami/openldap:latest
      ports:
        - "1389:1389"
        - "1636:1636"
      environment:
        - LDAP_ADMIN_USERNAME=admin
        - LDAP_ADMIN_PASSWORD=adminpassword
        - LDAP_USERS=user01,user02
        - LDAP_PASSWORDS=password1,password2
  

networks:
  internal:
