version: '3.8'
services:

  postgres_orm:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # redis:
  #   container_name: redis
  #   ports:
  #     - '8000:8000'
  #   build: .
  #   networks:
  #     - internal

  # redisinsight:
  #   container_name: redisinsight
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - '8001:8001'
  #   networks:
  #     - internal

networks:
  internal:
